- name: Развертывание на серверах из inventory.ini
  hosts: my_servers
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3.9
    new_user: Grigo6
    ssh_port: 10022

  roles:
    - common
    - user_management
    - software_installation
    - ssh_configuration
    - nginx_installation
    - web_page

  handlers:
    - name: Restart SSH service
      service:
        name: sshd
        state: restarted

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
