---
- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Enable and start Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Reload Nginx

- name: Copy custom index.html
  copy:
    content: |
      <html>
      <head><title>Курс системное администрирование</title></head>
      <body>
      <h1>Практическое задание</h1>
      </body>
      </html>
    dest: /usr/share/nginx/html/index.html
  notify: Reload Nginx