- name: Добавление нового пользователя
  user:
    name: "{{ new_user }}"
    state: present
    password: "Test12345"

- name: Добавление прав sudo
  become_user: root
  lineinfile:
    path: /etc/sudoers
    line: "{{ new_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s

- name: Создание нового SSH ключа для нового пользователя
  user:
    name: "{{ new_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_type: ed25519